engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.vue"
exclude_paths:
- "README.md"
- "LICENSE"
- "yarn.lock"
- "dist/assets/build.*"