language: node_js
node_js:
  - "6"
branches:
  only:
    - master
    - gh-pages
cache:
  yarn: true
  directories:
    - "node_modules"
script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist/
  target_branch: gh-pages
  name: Fernando Moreira
  email: nandomoreira.me@gmail.com
  on:
    branch: gh-pages
