language: node_js
node_js:
  - "6"
branches:
  only:
    - master
    - gh-pages
cache:
  yarn: true
  directories:
    - "node_modules"
before_script: "mkdir -p gh-pages"
script: "yarn deploy"
after_script: "ls -lah gh-pages/"
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: gh-pages