language: node_js
node_js:
  - "iojs"
  - "6"

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  target_branch: gh-pages
  name: Fernando Moreira
  email: nandomoreira.me@gmail.com
  on:
    branch: gh-pages
